<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ArtistsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('artists')->delete();
        
        \DB::table('artists')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Taeyong',
                'nationality' => 'Korean',
                'birthday' => '1995-07-01',
                'position' => 'Leader',
                'zodiac' => 'Cancer',
                'weight' => 58,
                'height' => 174,
                'blood_type' => 'O',
                'instagram' => 'taeoxo_nct',
                'ideal' => 'Someone who can teach me,leadme,and make up for my flaws',
                'photo' => 'https://kpopping.com/documents/88/0/800/Em30d1UUUAIADjc.jpeg',
                'group_id' => 2,
                'created_at' => '2021-10-23 13:59:26',
                'updated_at' => '2021-10-24 13:29:10',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Taeil',
                'nationality' => 'Korean',
                'birthday' => '1994-06-14',
                'position' => 'Leader',
                'zodiac' => 'Gemini',
                'weight' => 60,
                'height' => 171,
                'blood_type' => 'O',
                'instagram' => 'mo.on_air',
                'ideal' => 'Someone cute. He prefers short bob hair style',
                'photo' => 'https://kpopping.com/documents/24/4/800/EnCJP-OUYAAxnzg.jpeg',
                'group_id' => 2,
                'created_at' => '2021-10-23 13:59:26',
                'updated_at' => '2021-10-24 09:22:12',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Johnny',
                'nationality' => 'Americans',
                'birthday' => '1995-02-09',
                'position' => 'Leader',
                'zodiac' => 'Aquarius',
                'weight' => 70,
                'height' => 185,
                'blood_type' => 'B',
                'instagram' => 'johnnyjsuh',
            'ideal' => 'Someone who smiles at him a lot; a girl like Yoona (SNSD)',
                'photo' => 'https://kpopping.com/documents/a8/1/800/EnCJMYdVkAAtfAX.jpeg',
                'group_id' => 2,
                'created_at' => '2021-10-23 13:59:26',
                'updated_at' => '2021-10-24 09:21:54',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Yuta',
                'nationality' => 'Japanese',
                'birthday' => '1995-10-26',
                'position' => 'Leader',
                'zodiac' => 'Scorpio',
                'weight' => 60,
                'height' => 176,
                'blood_type' => 'A',
                'instagram' => 'yuu_taa_1026',
                'ideal' => 'A girl who has short hair, 15 cm shorter than him, has empathy towards people and does not “act pretty”',
                'photo' => 'https://kpopping.com/documents/6f/4/800/EnHRFbhVEAIa6YD.jpeg',
                'group_id' => 2,
                'created_at' => '2021-10-23 13:59:26',
                'updated_at' => '2021-10-24 09:24:55',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Kun',
                'nationality' => 'Chinese',
                'birthday' => '1996-01-01',
                'position' => 'Leader',
                'zodiac' => 'Capricorn',
                'weight' => 60,
                'height' => 176,
                'blood_type' => 'B',
                'instagram' => 'kun11xd',
                'ideal' => 'null',
                'photo' => 'https://kpopping.com/documents/06/2/800/EnCJTB5VoAEOkBf.jpeg',
                'group_id' => 2,
                'created_at' => '2021-10-23 13:59:26',
                'updated_at' => '2021-10-24 09:22:36',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Doyoung',
                'nationality' => 'Korean',
                'birthday' => '1996-02-01',
                'position' => 'Leader',
                'zodiac' => 'Aquarius',
                'weight' => 60,
                'height' => 178,
                'blood_type' => 'B',
                'instagram' => 'do0_nct',
                'ideal' => 'Someone who is polite.',
                'photo' => 'https://kpopping.com/documents/6e/5/800/Em88mIbVQAUDEap.jpeg',
                'group_id' => 2,
                'created_at' => '2021-10-23 13:59:26',
                'updated_at' => '2021-10-24 09:19:25',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Ten',
                'nationality' => 'Thai',
                'birthday' => '1996-02-27',
                'position' => 'Leader',
                'zodiac' => 'Pisces',
                'weight' => 59,
                'height' => 172,
                'blood_type' => 'A',
                'instagram' => 'tenlee_1001',
                'ideal' => 'he does not have an ideal type and he “likes a relationship which starts from learning about each other before developing to love”',
                'photo' => 'https://kpopping.com/documents/63/4/800/Em30qLsUUAAcOVI.jpeg',
                'group_id' => 2,
                'created_at' => '2021-10-23 13:59:26',
                'updated_at' => '2021-10-24 09:17:43',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'jaehyun',
                'nationality' => 'Korean',
                'birthday' => '1997-02-14',
                'position' => 'Leader',
                'zodiac' => 'Aquarius',
                'weight' => 63,
                'height' => 180,
                'blood_type' => 'A',
                'instagram' => '_jeongjaehyun',
                'ideal' => 'Women with straight and long hair. Someone who can communicate well with him. Someone who is kind. Someone he can depend on. Someone healthy and into sports. Someone who is usually calm but can also be cute. He doesn’t care if that person is older or younger.',
                'photo' => 'https://kpopping.com/documents/31/5/800/EnHQ88xUcAAOfrd.jpeg',
                'group_id' => 2,
                'created_at' => '2021-10-23 13:59:26',
                'updated_at' => '2021-10-24 09:23:07',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Winwin',
                'nationality' => 'Chinese',
                'birthday' => '1997-10-28',
                'position' => 'Leader',
                'zodiac' => 'Scorpio',
                'weight' => 60,
                'height' => 179,
                'blood_type' => 'B',
                'instagram' => 'wwiinn_7',
                'ideal' => 'Someone who has long black hair.',
                'photo' => 'https://kpopping.com/documents/65/1/800/Em88XdRUUAEtjvZ.jpeg',
                'group_id' => 2,
                'created_at' => '2021-10-23 13:59:26',
                'updated_at' => '2021-10-24 09:20:49',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Jungwoo',
                'nationality' => 'Korean',
                'birthday' => '1998-02-19',
                'position' => 'Leader',
                'zodiac' => 'Pisces',
                'weight' => 58,
                'height' => 180,
                'blood_type' => 'AB',
                'instagram' => 'ncit_kimjw',
                'ideal' => '',
                'photo' => 'https://kpopping.com/documents/6b/3/800/Em301ncVEAAtTnr.jpeg',
                'group_id' => 2,
                'created_at' => '2021-10-23 13:59:26',
                'updated_at' => '2021-10-24 09:21:04',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Lucas',
                'nationality' => 'half Chinese and half Thai',
                'birthday' => '1999-01-25',
                'position' => 'Leader',
                'zodiac' => 'Aquarius',
                'weight' => 64,
                'height' => 183,
                'blood_type' => 'O',
                'instagram' => 'lucas_xx444',
                'ideal' => '',
                'photo' => 'https://kpopping.com/documents/0b/1/800/EnCJIO1VkAArg6j.jpeg',
                'group_id' => 2,
                'created_at' => '2021-10-23 13:59:26',
                'updated_at' => '2021-10-24 09:21:41',
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Mark Lee',
                'nationality' => 'Canadian',
                'birthday' => '1999-08-02',
                'position' => 'Leader',
                'zodiac' => 'Leo',
                'weight' => 61,
                'height' => 175,
                'blood_type' => 'A',
                'instagram' => 'onyourm__ark',
                'ideal' => 'Someone who has long black hair',
                'photo' => 'https://kpopping.com/documents/d1/2/800/Em88bdDVQAAXyXy.jpeg',
                'group_id' => 2,
                'created_at' => '2021-10-23 13:59:26',
                'updated_at' => '2021-10-24 09:18:37',
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Xiaojun',
                'nationality' => 'Chinese',
                'birthday' => '1999-08-08',
                'position' => 'Leader',
                'zodiac' => 'Leo',
                'weight' => 58,
                'height' => 172,
                'blood_type' => 'A',
                'instagram' => 'djxiao_888',
                'ideal' => '',
                'photo' => 'https://kpopping.com/documents/25/2/800/EnHRBuMUUAoRSca.jpeg',
                'group_id' => 2,
                'created_at' => '2021-10-23 13:59:26',
                'updated_at' => '2021-10-24 09:24:35',
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Hendery',
                'nationality' => 'Macanese',
                'birthday' => '1999-09-28',
                'position' => 'Leader',
                'zodiac' => 'Libra',
                'weight' => 57,
                'height' => 175,
                'blood_type' => 'O',
                'instagram' => 'i_m_hendery',
                'ideal' => '',
                'photo' => 'https://kpopping.com/documents/90/0/800/EnCJgN1UYAoG9qv.jpeg',
                'group_id' => 2,
                'created_at' => '2021-10-23 13:59:26',
                'updated_at' => '2021-10-24 09:21:22',
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Renjun',
                'nationality' => 'Chinese',
                'birthday' => '2000-03-23',
                'position' => 'Leader',
                'zodiac' => 'Aries',
                'weight' => 57,
                'height' => 171,
                'blood_type' => 'O',
                'instagram' => 'yellow_3to3',
                'ideal' => '',
                'photo' => 'https://kpopping.com/documents/f2/4/800/EnHRJULVEAE0Op1.jpeg',
                'group_id' => 2,
                'created_at' => '2021-10-23 13:59:26',
                'updated_at' => '2021-10-24 09:25:24',
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Jeno',
                'nationality' => 'Korean',
                'birthday' => '2000-04-23',
                'position' => 'Leader',
                'zodiac' => 'Taurus',
                'weight' => 59,
                'height' => 176,
                'blood_type' => 'A',
                'instagram' => 'nct_dream',
                'ideal' => '',
                'photo' => 'https://kpopping.com/documents/90/1/800/Em30uAQUYAEB5Kc.jpeg',
                'group_id' => 2,
                'created_at' => '2021-10-23 13:59:26',
                'updated_at' => '2021-10-24 09:18:04',
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Haechan',
                'nationality' => 'Korean',
                'birthday' => '2000-06-06',
                'position' => 'Leader',
                'zodiac' => 'Gemini',
                'weight' => 58,
                'height' => 174,
                'blood_type' => 'AB',
                'instagram' => 'fullsun_ncit',
                'ideal' => '',
                'photo' => 'https://kpopping.com/documents/d3/2/800/EnHRNleUYAcQJKf.jpeg',
                'group_id' => 2,
                'created_at' => '2021-10-23 13:59:26',
                'updated_at' => '2021-10-24 09:25:42',
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'Jaemin',
                'nationality' => 'Korean',
                'birthday' => '2000-08-13',
                'position' => 'Leader',
                'zodiac' => 'Leo',
                'weight' => 58,
                'height' => 177,
                'blood_type' => 'AB',
                'instagram' => 'na.jaemin0813',
                'ideal' => '',
                'photo' => 'https://kpopping.com/documents/e4/1/800/Em88f--VkAEs53D.jpeg',
                'group_id' => 2,
                'created_at' => '2021-10-23 13:59:26',
                'updated_at' => '2021-10-24 09:18:50',
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'Yangyang',
                'nationality' => 'Chinese',
                'birthday' => '2000-10-10',
                'position' => 'Leader',
                'zodiac' => 'Libra',
                'weight' => 58,
                'height' => 174,
                'blood_type' => 'O',
                'instagram' => 'yangyang_x2',
                'ideal' => '',
                'photo' => 'https://kpopping.com/documents/f7/1/800/Em88qpLVEAwgpVR.jpeg',
                'group_id' => 2,
                'created_at' => '2021-10-23 13:59:26',
                'updated_at' => '2021-10-24 09:27:39',
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'Shotaro',
                'nationality' => 'Japanese',
                'birthday' => '2000-11-25',
                'position' => 'Leader',
                'zodiac' => 'Sagittarius',
                'weight' => 57,
                'height' => 178,
                'blood_type' => 'A',
                'instagram' => '_shotaroo_',
                'ideal' => '',
                'photo' => 'https://kpopping.com/documents/5f/3/800/Em30x41VEAA_PZK.jpeg',
                'group_id' => 2,
                'created_at' => '2021-10-23 13:59:26',
                'updated_at' => '2021-10-24 09:18:21',
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'Sungchan',
                'nationality' => 'Korean',
                'birthday' => '2001-09-13',
                'position' => 'Leader',
                'zodiac' => 'Virgo',
                'weight' => 65,
                'height' => 185,
                'blood_type' => 'A',
                'instagram' => 'nct',
                'ideal' => '',
                'photo' => 'https://kpopping.com/documents/99/2/800/Em30mRiVQAExQZJ.jpeg',
                'group_id' => 2,
                'created_at' => '2021-10-23 13:59:26',
                'updated_at' => '2021-10-24 09:17:25',
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'Chenle',
                'nationality' => 'Chinese',
                'birthday' => '2001-11-22',
                'position' => 'Leader',
                'zodiac' => 'Scorpio',
                'weight' => 58,
                'height' => 176,
                'blood_type' => 'O',
                'instagram' => 'nct_dream',
                'ideal' => '',
                'photo' => 'https://kpopping.com/documents/9c/2/800/Em88ip7VQAAgSbq.jpeg',
                'group_id' => 2,
                'created_at' => '2021-10-23 13:59:26',
                'updated_at' => '2021-10-24 09:19:07',
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'Jisung',
                'nationality' => 'Korean',
                'birthday' => '2002-02-05',
                'position' => 'Leader',
                'zodiac' => 'Aquarius',
                'weight' => 61,
                'height' => 180,
                'blood_type' => 'O',
                'instagram' => 'nct_dream',
                'ideal' => '',
                'photo' => 'https://kpopping.com/documents/70/4/800/EnCJWNxUUAIUQDW.jpeg',
                'group_id' => 2,
                'created_at' => '2021-10-23 13:59:26',
                'updated_at' => '2021-10-24 09:22:49',
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'Suho',
                'nationality' => 'Korean',
                'birthday' => '1991-03-22',
                'position' => 'Leader',
                'zodiac' => 'Gemini',
                'weight' => 65,
                'height' => 173,
                'blood_type' => 'AB',
                'instagram' => 'kimjuncotton',
                'ideal' => 'A girl with literary interests and has long straight hair',
            'photo' => 'https://kpopping.com/documents/c9/2/800/EXO-Special-Album-DON-T-FIGHT-THE-FEELING-Concept-Teasers-documents-7(5).jpeg',
                'group_id' => 1,
                'created_at' => '2021-10-23 13:59:26',
                'updated_at' => '2021-10-24 10:00:13',
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'Baekhyun',
                'nationality' => 'Korean',
                'birthday' => '1992-03-06',
                'position' => 'Leader',
                'zodiac' => 'Taurus',
                'weight' => 53,
                'height' => 174,
                'blood_type' => 'O',
                'instagram' => 'baekhynee_exo',
                'ideal' => 'A woman full of charms',
            'photo' => 'https://kpopping.com/documents/a0/5/800/EXO-Special-Album-DON-T-FIGHT-THE-FEELING-Concept-Teasers-documents-4(15).jpeg',
                'group_id' => 1,
                'created_at' => '2021-10-23 13:59:26',
                'updated_at' => '2021-10-24 10:00:32',
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'Chanyeol',
                'nationality' => 'Korean',
                'birthday' => '1992-12-27',
                'position' => 'Leader',
                'zodiac' => 'Aries',
                'weight' => 70,
                'height' => 186,
                'blood_type' => 'A',
                'instagram' => 'real_pcy',
                'ideal' => 'Someone who is sincere, cute, and smiles a lot',
            'photo' => 'https://kpopping.com/documents/19/4/800/EXO-Special-Album-DON-T-FIGHT-THE-FEELING-Concept-Teasers-documents-3(20).jpeg',
                'group_id' => 1,
                'created_at' => '2021-10-23 13:59:26',
                'updated_at' => '2021-10-24 10:01:27',
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'D.O.',
                'nationality' => 'Korean',
                'birthday' => '1993-01-12',
                'position' => 'Leader',
                'zodiac' => 'Aries',
                'weight' => 59,
                'height' => 173,
                'blood_type' => 'A',
                'instagram' => 'weareone.exo',
                'ideal' => 'A girl who is kind and eats well',
            'photo' => 'https://kpopping.com/documents/32/2/800/EXO-Special-Album-DON-T-FIGHT-THE-FEELING-Concept-Teasers-documents-2(20).jpeg',
                'group_id' => 1,
                'created_at' => '2021-10-23 13:59:26',
                'updated_at' => '2021-10-24 09:58:52',
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'Kai',
                'nationality' => 'Korean',
                'birthday' => '1994-01-14',
                'position' => 'Leader',
                'zodiac' => 'Aries',
                'weight' => 65,
                'height' => 182,
                'blood_type' => 'A',
                'instagram' => 'zkdlin',
                'ideal' => 'Someone like Han Ye Seul',
            'photo' => 'https://kpopping.com/documents/9f/5/800/EXO-Special-Album-DON-T-FIGHT-THE-FEELING-Concept-Teasers-documents-6(9).jpeg',
                'group_id' => 1,
                'created_at' => '2021-10-23 13:59:26',
                'updated_at' => '2021-10-24 10:00:47',
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'Sehun',
                'nationality' => 'Korean',
                'birthday' => '1994-04-12',
                'position' => 'Leader',
                'zodiac' => 'Aries',
                'weight' => 63,
                'height' => 183,
                'blood_type' => 'O',
                'instagram' => 'oohsehun',
                'ideal' => 'A woman that is kind',
            'photo' => 'https://kpopping.com/documents/5c/1/800/EXO-Special-Album-DON-T-FIGHT-THE-FEELING-Concept-Teasers-documents-6(10).jpeg',
                'group_id' => 1,
                'created_at' => '2021-10-23 13:59:26',
                'updated_at' => '2021-10-24 10:01:40',
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'Xiumin',
                'nationality' => 'Korean',
                'birthday' => '1990-04-26',
                'position' => 'Leader',
                'zodiac' => 'Aries',
                'weight' => 53,
                'height' => 173,
                'blood_type' => 'B',
                'instagram' => 'e_xiu_o',
                'ideal' => 'Someone who is hug-able and can give comfort to others',
            'photo' => 'https://kpopping.com/documents/b0/5/800/EXO-Special-Album-DON-T-FIGHT-THE-FEELING-Concept-Teasers-documents-2(19).jpeg',
                'group_id' => 1,
                'created_at' => '2021-10-23 13:59:26',
                'updated_at' => '2021-10-24 09:58:02',
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'Chen',
                'nationality' => 'Korean',
                'birthday' => '1992-09-21',
                'position' => 'Leader',
                'zodiac' => 'Virgo',
                'weight' => 60,
                'height' => 173,
                'blood_type' => 'B',
                'instagram' => 'weareone.exo',
                'ideal' => 'Someone who is like a noona: someone that would take good care of him',
                'photo' => 'https://cms.dmpcdn.com/musicarticle/2021/02/17/4cfb15e0-7109-11eb-85b4-d74ed7823c07_original.png',
                'group_id' => 1,
                'created_at' => '2021-10-23 13:59:26',
                'updated_at' => '2021-10-24 10:03:46',
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'Choi Hyunsuk',
                'nationality' => 'Korean',
                'birthday' => '1999-04-21',
                'position' => 'Leader',
                'zodiac' => 'Taurus',
                'weight' => 58,
                'height' => 171,
                'blood_type' => 'A',
                'instagram' => 'yg_treasure_official',
                'ideal' => '',
                'photo' => 'https://0.soompi.io/wp-content/uploads/2020/12/04070821/treasure-2.jpeg',
                'group_id' => 3,
                'created_at' => '2021-10-23 13:59:26',
                'updated_at' => '2021-10-24 09:06:42',
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'Jihoon',
                'nationality' => 'Korean',
                'birthday' => '2000-03-14',
                'position' => 'Leader',
                'zodiac' => 'Pisces',
                'weight' => 69,
                'height' => 178,
                'blood_type' => 'B',
                'instagram' => 'yg_treasure_official',
                'ideal' => '',
                'photo' => 'https://0.soompi.io/wp-content/uploads/2020/12/05071422/treasure-31.jpeg',
                'group_id' => 3,
                'created_at' => '2021-10-23 13:59:26',
                'updated_at' => '2021-10-24 09:05:51',
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'Yoshi',
                'nationality' => 'Japanese',
                'birthday' => '2000-05-15',
                'position' => 'Leader',
                'zodiac' => 'Taurus',
                'weight' => 66,
                'height' => 179,
                'blood_type' => 'A',
                'instagram' => 'yg_treasure_official',
                'ideal' => '',
                'photo' => 'https://0.soompi.io/wp-content/uploads/2020/12/06072837/treasure-32.jpeg',
                'group_id' => 3,
                'created_at' => '2021-10-23 13:59:26',
                'updated_at' => '2021-10-24 09:05:03',
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'Junkyu',
                'nationality' => 'Korean',
                'birthday' => '2000-09-09',
                'position' => 'Leader',
                'zodiac' => 'Virgo',
                'weight' => 65,
                'height' => 178,
                'blood_type' => 'O',
                'instagram' => 'yg_treasure_official',
                'ideal' => '',
                'photo' => 'https://0.soompi.io/wp-content/uploads/2020/12/07072950/junkyu.jpeg',
                'group_id' => 3,
                'created_at' => '2021-10-23 13:59:26',
                'updated_at' => '2021-10-24 09:04:31',
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'Mashiho',
                'nationality' => 'Japanese',
                'birthday' => '2001-03-25',
                'position' => 'Leader',
                'zodiac' => 'Aries',
                'weight' => 60,
                'height' => 169,
                'blood_type' => 'AB',
                'instagram' => 'yg_treasure_official',
                'ideal' => '',
                'photo' => 'https://0.soompi.io/wp-content/uploads/2020/12/07073008/mashiho.jpeg',
                'group_id' => 3,
                'created_at' => '2021-10-23 13:59:26',
                'updated_at' => '2021-10-24 09:04:18',
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'Yoon Jaehyuk',
                'nationality' => 'Korean',
                'birthday' => '2001-07-23',
                'position' => 'Leader',
                'zodiac' => 'Leo',
                'weight' => 63,
                'height' => 178,
                'blood_type' => 'O',
                'instagram' => 'yg_treasure_official',
                'ideal' => '',
                'photo' => 'https://0.soompi.io/wp-content/uploads/2020/12/04070758/treasure-3.jpeg',
                'group_id' => 3,
                'created_at' => '2021-10-23 13:59:26',
                'updated_at' => '2021-10-24 09:07:00',
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'Asahi',
                'nationality' => 'Japanese',
                'birthday' => '2001-08-20',
                'position' => 'Leader',
                'zodiac' => 'Leo',
                'weight' => 57,
                'height' => 173,
                'blood_type' => 'AB',
                'instagram' => 'yg_treasure_official',
                'ideal' => '',
                'photo' => 'https://0.soompi.io/wp-content/uploads/2020/12/05071501/treasure-11.jpeg',
                'group_id' => 3,
                'created_at' => '2021-10-23 13:59:26',
                'updated_at' => '2021-10-24 09:03:34',
            ),
            38 => 
            array (
                'id' => 39,
                'name' => 'Bang Yedam',
                'nationality' => 'Korean',
                'birthday' => '2002-05-07',
                'position' => 'Leader',
                'zodiac' => 'Taurus',
                'weight' => 61,
                'height' => 172,
                'blood_type' => 'A',
                'instagram' => 'yg_treasure_official',
                'ideal' => '',
                'photo' => 'https://0.soompi.io/wp-content/uploads/2020/12/06072900/treasure-22.jpeg',
                'group_id' => 3,
                'created_at' => '2021-10-23 13:59:26',
                'updated_at' => '2021-10-24 09:04:47',
            ),
            39 => 
            array (
                'id' => 40,
                'name' => 'Doyoung',
                'nationality' => 'Korean',
                'birthday' => '2003-12-04',
                'position' => 'Leader',
                'zodiac' => 'Sagittarius',
                'weight' => 58,
                'height' => 177,
                'blood_type' => 'B',
                'instagram' => 'yg_treasure_official',
                'ideal' => '',
                'photo' => 'https://0.soompi.io/wp-content/uploads/2020/12/05071442/treasure-21.jpeg',
                'group_id' => 3,
                'created_at' => '2021-10-23 13:59:26',
                'updated_at' => '2021-10-24 09:06:07',
            ),
            40 => 
            array (
                'id' => 41,
                'name' => 'Haruto',
                'nationality' => 'Japanese',
                'birthday' => '2004-04-05',
                'position' => 'Leader',
                'zodiac' => 'Aries',
                'weight' => 65,
                'height' => 185,
                'blood_type' => 'B',
                'instagram' => 'yg_treasure_official',
                'ideal' => '',
                'photo' => 'https://0.soompi.io/wp-content/uploads/2020/12/06072812/treasure-5.jpeg',
                'group_id' => 3,
                'created_at' => '2021-10-23 13:59:26',
                'updated_at' => '2021-10-24 09:05:34',
            ),
            41 => 
            array (
                'id' => 42,
                'name' => 'Park Jeongwoo',
                'nationality' => 'Korean',
                'birthday' => '2004-09-28',
                'position' => 'Leader',
                'zodiac' => 'Libra',
                'weight' => 65,
                'height' => 180,
                'blood_type' => 'O',
                'instagram' => 'yg_treasure_official',
                'ideal' => '',
                'photo' => 'https://0.soompi.io/wp-content/uploads/2020/12/07073025/park-jeong-woo-.jpeg',
                'group_id' => 3,
                'created_at' => '2021-10-23 13:59:26',
                'updated_at' => '2021-10-24 09:04:04',
            ),
            42 => 
            array (
                'id' => 43,
                'name' => 'Junghwan',
                'nationality' => 'Korean',
                'birthday' => '2005-02-18',
                'position' => 'Leader',
                'zodiac' => 'Aquarius',
                'weight' => 67,
                'height' => 179,
                'blood_type' => 'B',
                'instagram' => 'yg_treasure_official',
                'ideal' => '',
                'photo' => 'https://0.soompi.io/wp-content/uploads/2020/12/04070839/treasure-1.jpeg',
                'group_id' => 3,
                'created_at' => '2021-10-23 13:59:26',
                'updated_at' => '2021-10-24 09:06:26',
            ),
            43 => 
            array (
                'id' => 44,
                'name' => 'Jisoo',
                'nationality' => 'Korean',
                'birthday' => '1995-01-03',
                'position' => 'Leader',
                'zodiac' => 'Capricorn',
                'weight' => 44,
                'height' => 162,
                'blood_type' => 'A',
                'instagram' => 'sooyaaa__',
                'ideal' => 'Someone who is really into her or who smiles pretty',
                'photo' => 'https://pbs.twimg.com/media/EggR5k1U8AEDQ0x?format=jpg&name=large',
                'group_id' => 4,
                'created_at' => '2021-10-24 07:14:20',
                'updated_at' => '2021-10-24 08:47:18',
            ),
            44 => 
            array (
                'id' => 45,
                'name' => 'Jennie',
                'nationality' => 'Korean',
                'birthday' => '1996-01-16',
                'position' => 'Leader',
                'zodiac' => 'Capricorn',
                'weight' => 45,
                'height' => 163,
                'blood_type' => 'B',
                'instagram' => 'jennierubyjane',
                'ideal' => 'Someone who is a hard worker',
                'photo' => 'https://pbs.twimg.com/media/EggR5k6U0AEUdRs?format=jpg&name=large',
                'group_id' => 4,
                'created_at' => '2021-10-24 07:18:40',
                'updated_at' => '2021-10-24 08:47:00',
            ),
            45 => 
            array (
                'id' => 46,
                'name' => 'Rosé',
                'nationality' => 'Korean-New Zealand',
                'birthday' => '1997-02-11',
                'position' => 'Leader',
                'zodiac' => 'Aquarius',
                'weight' => 44,
                'height' => 168,
                'blood_type' => 'B',
                'instagram' => 'roses_are_rosie',
                'ideal' => 'Someone nice and genuine, with a good/ unique voice. She said there are many sunbaenims with great voices, but among them, Big Bang stand out',
                'photo' => 'https://pbs.twimg.com/media/EggR5k5UMAAh0DX?format=jpg&name=large',
                'group_id' => 4,
                'created_at' => '2021-10-24 07:31:37',
                'updated_at' => '2021-10-24 08:46:45',
            ),
            46 => 
            array (
                'id' => 47,
                'name' => 'Lisa',
                'nationality' => 'Thai',
                'birthday' => '1997-03-27',
                'position' => 'Leader',
                'zodiac' => 'Aries',
                'weight' => 44,
                'height' => 166,
                'blood_type' => 'O',
                'instagram' => 'lalalalisa_m',
                'ideal' => 'She said she likes older guys, who can take good care of her. Also she likes kindhearted men, who can cook and who have a lifestyle that fits hers',
                'photo' => 'https://pbs.twimg.com/media/EggR5k5U4AETufG?format=jpg&name=large',
                'group_id' => 4,
                'created_at' => '2021-10-24 07:34:54',
                'updated_at' => '2021-10-24 08:46:26',
            ),
            47 => 
            array (
                'id' => 48,
                'name' => 'RM',
                'nationality' => 'Korean',
                'birthday' => '1994-09-12',
                'position' => 'Leader',
                'zodiac' => 'Virgo',
                'weight' => 73,
                'height' => 180,
                'blood_type' => 'A',
                'instagram' => 'bts.bighitofficial',
                'ideal' => 'Sexy, even to a brain. Someone that is thoughtful and confident',
                'photo' => 'https://s.isanook.com/jo/0/ui/486/2433525/rm2.jpg',
                'group_id' => 5,
                'created_at' => '2021-10-24 08:05:59',
                'updated_at' => '2021-10-24 08:32:38',
            ),
            48 => 
            array (
                'id' => 49,
                'name' => 'Jin',
                'nationality' => 'Korean',
                'birthday' => '1992-12-04',
                'position' => 'Leader',
                'zodiac' => 'Sagittarius',
                'weight' => 63,
                'height' => 178,
                'blood_type' => 'O',
                'instagram' => 'bts.bighitofficial',
                'ideal' => 'A girl whose looks and personality is similar to that of a puppy, who’s good at cooking, kind and takes good care of him',
                'photo' => 'https://s.isanook.com/jo/0/ui/486/2433525/jin1.jpg',
                'group_id' => 5,
                'created_at' => '2021-10-24 08:08:18',
                'updated_at' => '2021-10-24 08:32:58',
            ),
            49 => 
            array (
                'id' => 50,
                'name' => 'Suga',
                'nationality' => 'Korean',
                'birthday' => '1993-03-09',
                'position' => 'Leader',
                'zodiac' => 'Pisces',
                'weight' => 59,
                'height' => 174,
                'blood_type' => 'O',
                'instagram' => 'bts.bighitofficial',
                'ideal' => 'A girl who likes music, especially hip-hop',
                'photo' => 'https://s.isanook.com/jo/0/ui/486/2433525/suga1.jpg',
                'group_id' => 5,
                'created_at' => '2021-10-24 08:10:08',
                'updated_at' => '2021-10-24 08:33:25',
            ),
            50 => 
            array (
                'id' => 51,
                'name' => 'J-Hope',
                'nationality' => 'Korean',
                'birthday' => '1994-02-18',
                'position' => 'Leader',
                'zodiac' => 'Aquarius',
                'weight' => 65,
                'height' => 177,
                'blood_type' => 'A',
                'instagram' => 'bts.bighitofficial',
                'ideal' => 'A girl who loves him, is good at cooking, and thinks a lot',
                'photo' => 'https://s.isanook.com/jo/0/ui/486/2433525/j-hope1.jpg',
                'group_id' => 5,
                'created_at' => '2021-10-24 08:11:54',
                'updated_at' => '2021-10-24 08:33:49',
            ),
            51 => 
            array (
                'id' => 52,
                'name' => 'Jimin',
                'nationality' => 'Korean',
                'birthday' => '1995-10-13',
                'position' => 'Leader',
                'zodiac' => 'Libra',
                'weight' => 58,
                'height' => 174,
                'blood_type' => 'A',
                'instagram' => 'bts.bighitofficial',
                'ideal' => 'A nice and cute girl who is smaller than him',
                'photo' => 'https://s.isanook.com/jo/0/ui/486/2433525/jimin1.jpg',
                'group_id' => 5,
                'created_at' => '2021-10-24 08:13:38',
                'updated_at' => '2021-10-24 08:34:19',
            ),
            52 => 
            array (
                'id' => 53,
                'name' => 'V',
                'nationality' => 'Korean',
                'birthday' => '1995-12-30',
                'position' => 'Leader',
                'zodiac' => 'Capricorn',
                'weight' => 63,
                'height' => 178,
                'blood_type' => 'AB',
                'instagram' => 'bts.bighitofficial',
                'ideal' => 'Someone who takes care of him and loves only him and who has a lot of aegyo',
                'photo' => 'https://s.isanook.com/jo/0/ui/486/2433525/v1.jpg',
                'group_id' => 5,
                'created_at' => '2021-10-24 08:15:10',
                'updated_at' => '2021-10-24 08:31:36',
            ),
            53 => 
            array (
                'id' => 54,
                'name' => 'Jungkook',
                'nationality' => 'Korean',
                'birthday' => '1997-09-01',
                'position' => 'Leader',
                'zodiac' => 'Virgo',
                'weight' => 66,
                'height' => 178,
                'blood_type' => 'A',
                'instagram' => 'bts.bighitofficial',
                'ideal' => 'Someone who’s at least 168 cm but smaller than him, is a good wife, good at cooking, smart, has pretty legs, and is nice. Also a girl who likes him and is good at singing',
                'photo' => 'https://s.isanook.com/jo/0/ui/486/2433525/jungkook1.jpg',
                'group_id' => 5,
                'created_at' => '2021-10-24 08:17:41',
                'updated_at' => '2021-10-24 08:32:11',
            ),
        ));
        
        
    }
}